---
galaxy_info:
  role_name: step_ca
  author: wtcross
  description: Deploys step-ca via Podman Quadlet with PKCS#11/HSM support
  license: MIT-0
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "10"

  galaxy_tags:
    - pki
    - step
    - certificate
    - ca
    - hsm
    - pkcs11
    - podman
    - quadlet

dependencies: []
