---
galaxy_info:
  role_name: step_host
  author: wtcross
  description: Prepares the host OS with required packages for step-ca deployment
  license: MIT-0
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "10"

  galaxy_tags:
    - pki
    - step
    - certificate
    - ca
    - hsm
    - pkcs11

dependencies: []
