---
- name: Ensure firewalld is enabled
  become: true
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: firewalld

- name: Ensure traffic to the step-ca-p11-kit service ({{ _step_https_port }}/tcp) is allowed
  become: true
  ansible.posix.firewalld:
    port: "{{ _step_https_port }}/tcp"
    immediate: true
    permanent: true
    state: enabled
