---
- name: Include preflight checks
  ansible.builtin.include_tasks: preflight-checks.yaml

- name: Include upstream asset synchronization tasks
  ansible.builtin.include_tasks: fetch-upstream-assets.yaml

- name: Include podman secret tasks
  ansible.builtin.include_tasks: podman-secret.yaml

- name: Include quadlet tasks
  ansible.builtin.include_tasks: quadlet.yaml

- name: Include firewall tasks
  ansible.builtin.include_tasks: firewall.yaml
