---
- name: Restart polkit
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    name: polkit
    enabled: true
    scope: system

- name: Restart the systemd-logind service
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    name: systemd-logind
